name: irrigatech
description: IrrigaTech — Smart Irrigation. Effortless Farming.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_riverpod: 2.6.1
  go_router: 14.6.2
  google_fonts: 6.2.1
  lottie: 3.1.3
  fl_chart: 0.69.2
  flutter_secure_storage: 9.2.2
  flutter_local_notifications: 18.0.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_animate: 4.5.2
  connectivity_plus: 6.1.1
  dio: 5.7.0
  intl: 0.19.0
  shared_preferences: 2.3.3
  firebase_core: 3.8.1
  firebase_auth: 5.3.4
  google_sign_in: 6.2.2
  cloud_firestore: 5.6.0
  firebase_messaging: 15.1.6
  uuid: 4.5.1
  path_provider: 2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  flutter_launcher_icons: 0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/lottie/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#0D9488"
  adaptive_icon_foreground: assets/icon/app_icon.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/icon/app_icon.png
    background_color: "#0D9488"
    theme_color: "#10B981"
